import {
  User,
  Building2,
  Calendar,
  Clock,
  Briefcase,
  Mail,
  MapPin,
  ShieldCheck,
} from "lucide-react";

function HostEmailPreview({ meeting }) {
  if (!meeting) return null;

  return (
    <div className="bg-white rounded-3xl overflow-hidden shadow-xl">

      {/* Email Header */}

      <div className="bg-gradient-to-r from-blue-700 via-cyan-600 to-blue-500 px-10 py-8">

        <div className="flex justify-between items-center">

          <div>

            <h1 className="text-3xl font-bold text-white">
              S3D Technologies
            </h1>

            <p className="text-blue-100 mt-2">
              Visitor Management System
            </p>

          </div>

          <Mail
            size={55}
            className="text-white"
          />

        </div>

      </div>

      {/* Body */}

      <div className="p-10">

        <h2 className="text-2xl font-bold text-slate-800">

          New Meeting Request

        </h2>

        <p className="mt-4 text-slate-600 leading-7">

          Dear <strong>{meeting.host || "Host"}</strong>,

          <br /><br />

          A visitor meeting has been scheduled for you.

          Please review the meeting details below.

        </p>

        {/* Details */}

        <div className="grid md:grid-cols-2 gap-6 mt-10">

          <Info
            icon={User}
            label="Visitor"
            value={meeting.name}
          />

          <Info
            icon={Building2}
            label="Company"
            value={meeting.company}
          />

          <Info
            icon={Briefcase}
            label="Purpose"
            value={meeting.purpose}
          />

          <Info
            icon={Calendar}
            label="Meeting Date"
            value={meeting.date}
          />

          <Info
            icon={Clock}
            label="Meeting Time"
            value={meeting.time}
          />

          <Info
            icon={MapPin}
            label="Department"
            value={meeting.department}
          />

        </div>

        {/* Meeting Link */}

        <div className="mt-10 bg-slate-100 border rounded-2xl p-6">

          <h3 className="font-bold text-lg">

            Secure Meeting Link

          </h3>

          <p className="text-slate-600 mt-3 break-all">

            {meeting.meetingUrl}

          </p>

        </div>

        {/* Security */}

        <div className="mt-8 flex items-center gap-3 rounded-xl bg-green-50 border border-green-200 p-5">

          <ShieldCheck className="text-green-600" />

          <p className="text-green-700">

            This meeting invitation is securely generated by the
            Visitor Management System.

          </p>

        </div>

        {/* Buttons */}

        <div className="flex gap-5 mt-10">

          <button
            className="
            px-8
            py-4
            rounded-xl
            bg-green-600
            hover:bg-green-700
            text-white
            font-semibold
            transition
            "
          >
            Accept Meeting
          </button>

          <button
            className="
            px-8
            py-4
            rounded-xl
            bg-red-600
            hover:bg-red-700
            text-white
            font-semibold
            transition
            "
          >
            Reject Meeting
          </button>

        </div>

      </div>

      {/* Footer */}

      <div className="bg-slate-100 px-10 py-6 border-t">

        <p className="text-sm text-slate-500">

          © {new Date().getFullYear()} S3D Technologies Pvt. Ltd.

          <br />

          Visitor Management System

        </p>

      </div>

    </div>
  );
}

function Info({
  icon: Icon,
  label,
  value,
}) {
  return (
    <div className="flex gap-4 rounded-xl border p-5">

      <div className="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">

        <Icon
          className="text-blue-600"
          size={22}
        />

      </div>

      <div>

        <p className="text-sm text-slate-500">

          {label}

        </p>

        <h3 className="font-semibold text-slate-800 mt-1">

          {value || "--"}

        </h3>

      </div>

    </div>
  );
}

export default HostEmailPreview;